# Generated by Django 6.0.6 on 2026-07-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionresult',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='bid_increment',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='current_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auctionresult',
            name='final_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.IntegerField(),
        ),
    ]
