# Generated by Django 6.0.6 on 2026-06-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_alter_auction_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bid_increment',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
        ),
    ]
