# Generated by Django 6.0.6 on 2026-06-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionresult_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
