# Generated by Django 6.0.6 on 2026-07-02 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_item_image_alter_item_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='current_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions_winning', to=settings.AUTH_USER_MODEL),
        ),
    ]
